{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#  Principes de l'Informatique et Gestion de Données avec Excel \n",
    "\n",
    "## **Comment fonctionne un ordinateur ?**\n",
    "\n",
    "\n",
    "Interagir avec un ordinateur est une expérience très interactive :\n",
    "\n",
    "- **Lorsque nous tapons sur un clavier**, l'ordinateur reconnaît et affiche les caractères correspondants.\n",
    "- **Lorsque nous bougeons la souris**, l'ordinateur crée un curseur qui suit ces mouvements.\n",
    "\n",
    "Mais comment un ordinateur peut-il comprendre et répondre à nos actions ?\n",
    "\n",
    "Dans cette leçon, nous explorerons les quatre fonctions principales qui permettent à un ordinateur de répondre à nos interactions :\n",
    "\n",
    "- **Entrée** : Comment les actions comme les clics et les frappes sont captées.\n",
    "- **Traitement** : L'analyse et la réponse aux entrées.\n",
    "- **Mémoire** : Où les informations sont stockées temporairement ou de manière permanente.\n",
    "- **Sortie** : Comment les résultats sont affichés ou reproduits.\n",
    "\n",
    "Chaque fonction est cruciale pour permettre à l'ordinateur de fonctionner de manière efficace et réactive."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Comprendre les entrées d'un ordinateur\n",
    "\n",
    "Les entrées sur un ordinateur proviennent de nos interactions quotidiennes, comme cliquer sur une souris ou ajuster le volume. Ce sont des commandes physiques transformées en données numériques que l'ordinateur peut comprendre et traiter.\n",
    "\n",
    "Voici comment cela fonctionne :\n",
    "\n",
    "1. **Connexion** : Les dispositifs d'entrée (souris, clavier, etc.) sont connectés à l'ordinateur, généralement via un port sur la carte mère.\n",
    "2. **Détection et signalisation** : Le dispositif d'entrée détecte nos actions (comme un clic) et envoie un signal au processeur central (CPU).\n",
    "3. **Conversion en binaire** : Le signal est converti en code binaire, un langage composé uniquement de 0 et de 1, que le CPU peut traiter.\n",
    "\n",
    "En bref, nos actions physiques sont converties en instructions numériques que l'ordinateur exécute."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "\n",
    "### Traitement des données\n",
    "\n",
    "\n",
    "\n",
    "Après avoir reçu des données, notre ordinateur doit les traiter pour comprendre nos demandes et savoir comment y répondre. Cette mission est dévolue au processeur central, ou CPU, le \"cerveau\" de l'ordinateur.\n",
    "\n",
    "#### Rôle du CPU\n",
    "Le CPU joue un rôle central, gérant la communication entre le matériel (hardware) et le logiciel (software) :\n",
    "- **Interprétation des actions** : Si nous augmentons le volume sur nos haut-parleurs, le CPU reçoit et interprète ces données.\n",
    "- **Exécution des logiciels** : Lorsque nous lançons un logiciel, le CPU traite toutes les opérations nécessaires pour que le logiciel fonctionne correctement.\n",
    "\n",
    "Avec la multitude de logiciels et de processus que nous utilisons, le CPU doit traiter les informations rapidement. C’est là que la mémoire de l'ordinateur intervient pour aider à la gestion efficace de ces données."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Gestion de la mémoire dans les ordinateurs\n",
    "La mémoire d'un ordinateur est essentielle pour stocker et accéder aux informations, que ce soit temporairement ou de manière permanente. Comment cela fonctionne-t-il ?\n",
    "\n",
    "#### Mémoire Temporaire (RAM)\n",
    "La mémoire temporaire, ou RAM, est utilisée pour des informations dont nous avons besoin brièvement. Par exemple, le numéro de téléphone d'un restaurant ne doit être retenu que le temps de passer une commande. De même, lorsqu'un logiciel est en cours d'utilisation, la RAM stocke temporairement les instructions nécessaires pour que le CPU puisse les exécuter rapidement. Cependant, une fois le programme fermé ou l'ordinateur éteint, ces données disparaissent.\n",
    "\n",
    "#### Mémoire Permanente (Disque dur)\n",
    "Pour des données à conserver sur le long terme, comme des centaines de photos, nous utilisons la mémoire permanente. Ces données sont généralement sauvegardées sur le disque dur de l'ordinateur, permettant un accès durable et répété à ces informations.\n",
    "\n",
    "En résumé, la mémoire d'un ordinateur travaille de concert pour gérer efficacement les informations nécessaires à court terme via la RAM, et celles à conserver durablement sur le disque dur."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Sortie\n",
    "\n",
    "\n",
    "Une fois que le CPU a traité les données et envoyé des instructions sur leur gestion, une sortie est produite ! La sortie peut être vue comme l'exécution de la commande que nous avons donnée via un dispositif de sortie.\n",
    "\n",
    "Voici quelques exemples de dispositifs de sortie :\n",
    "\n",
    "- **Moniteurs**\n",
    "- **Haut-parleurs**\n",
    "- **Imprimantes**\n",
    "\n",
    "Par exemple, si nous cliquons sur une souris pour ouvrir un fichier, la sortie sera le contenu du fichier affiché sur le moniteur. Si nous augmentons le volume de nos haut-parleurs, la sortie sera le son qui devient plus fort.\n",
    "\n",
    "La sortie représente l'étape finale dans le processus d'interaction avec notre ordinateur."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Système de Numération Binaire\n",
    "\n",
    "### Introduction\n",
    "Comme le dit la vieille blague :\n",
    "\n",
    "***Il y a seulement 10 types de personnes dans le monde, celles qui comprennent le binaire et celles qui ne le comprennent pas.***\n",
    "\n",
    "Le binaire est défini comme quelque chose qui concerne, est composé de, ou implique deux éléments.\n",
    "\n",
    "En informatique, les exemples de binaire se divisent en deux catégories distinctes :\n",
    "\n",
    "- **Nombres Binaires**\n",
    "- **Données Binaires**\n",
    "\n",
    "Les nombres binaires sont exprimés par une combinaison de 0 et de 1. Par exemple, 100110 est l'équivalent binaire du nombre 38.\n",
    "\n",
    "Parmi les exemples courants de données binaires, on trouve :\n",
    "\n",
    "- **Code Machine** (001010101100111001010010011)\n",
    "- **Expressions Booléennes** (Vrai ou Faux)\n",
    "- **États Matériels** (Allumé ou Éteint)\n",
    "- **Réseautique et Stockage de Fichiers**\n",
    "\n",
    "Avant de plonger dans l'utilisation des données, prenons le temps de vraiment comprendre ce que sont les données binaires et le système de numération binaire."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Ordinateurs et Système Binaire\n",
    "\n",
    "Les ordinateurs fonctionnent avec le système binaire, utilisant uniquement deux états, off (0) et on (1), car gérer dix états différents comme dans le système décimal serait trop coûteux et complexe. Cette simplicité permet aux ordinateurs de traiter les données efficacement.\n",
    "\n",
    "Les données binaires sont traitées soit comme de l'énergie appliquée, soit comme de l'énergie non appliquée, nécessitant une grande précision dans la gestion de la tension électrique. Les données ont des longueurs spécifiques, comme les octets (8 bits) et les mots (16 bits), facilitant leur traitement par le matériel.\n",
    "\n",
    "Par exemple, la vitesse d'internet est mesurée en bits par seconde, tandis que la taille des fichiers est en octets. Un gigabit de vitesse internet (1 Gb/s) paraît rapide, mais comme un octet équivaut à huit bits, le téléchargement prendra en réalité huit fois plus de temps que prévu.\n",
    "\n",
    "En résumé, tout, du texte à l'image sur votre écran, est représenté par des combinaisons de 0 et de 1."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Système de Numération Binaire\n",
    "\n",
    "Les nombres ont été représentés de différentes manières à travers l'histoire. Par exemple, sur certaines horloges, vous pouvez voir que six heures est indiqué par VI, le chiffre romain pour 6.\n",
    "\n",
    "Le système de numération le plus réussi est appelé le système décimal, du mot latin \"dec-\" signifiant ensemble de dix ou ayant une base de dix.\n",
    "\n",
    "Bien que les origines exactes de ce système soient inconnues, il est clair qu'il a commencé avec le comptage sur nos doigts et a plus tard évolué en substituant les caractères hindou-arabes de 0, 1, 2, 3, 4, 5, 6, 7, 8 et 9 aux doigts pour effectuer des opérations plus importantes.\n",
    "\n",
    "Dans le système décimal, chaque chiffre peut être représenté par un multiple d'une puissance de dix et ajouté aux autres chiffres. Prenons le nombre 305.\n",
    "\n",
    "# IMAGE binaire 305\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Puissances et Règles de Calcul\n",
    "\n",
    "**Définition et exemples :**\n",
    "\n",
    "- **Puissance positive :** Multiplier un nombre par lui-même plusieurs fois.\n",
    "  - Exemples :\n",
    "    - $2^3 = 2 \\times 2 \\times 2 = 8$\n",
    "    - $4^2 = 4 \\times 4 = 16$\n",
    "\n",
    "- **Puissance zéro :** Tout nombre élevé à la puissance zéro est égal à 1.\n",
    "  - Exemple : $5^0 = 1$\n",
    "\n",
    "- **Puissance négative :** Correspond à l'inverse de la puissance positive.\n",
    "  - Exemple : $3^{-2} = \\frac{1}{3^2} = \\frac{1}{9}$\n",
    "\n",
    "**Règles de calcul des puissances :**\n",
    "\n",
    "- **Addition des exposants lors de la multiplication :**\n",
    "  - $x^{m+n} = x^m \\times x^n$\n",
    "  - Exemple : $2^3 \\times 2^4 = 2^{3+4} = 2^7 = 128$\n",
    "\n",
    "- **Soustraction des exposants lors de la division :**\n",
    "  - $\\frac{x^m}{x^n} = x^{m-n}$\n",
    "  - Exemple : $\\frac{5^4}{5^2} = 5^{4-2} = 5^2 = 25$\n",
    "\n",
    "- **Multiplication des exposants :**\n",
    "  - $(x^m)^n = x^{m \\times n}$\n",
    "  - Exemple : $(2^3)^2 = 2^{3 \\times 2} = 2^6 = 64$\n",
    "\n",
    "**Exercices :**\n",
    "1. Calculez les puissances suivantes :\n",
    "   - $3^4$\n",
    "   - $7^0$\n",
    "   - $5^{-2}$\n",
    "2. Simplifiez les expressions suivantes en utilisant les règles des puissances :\n",
    "   - $2^5 \\times 2^3$\n",
    "   - $\\frac{6^4}{6^2}$\n",
    "   - $(4^2)^3$\n",
    "3. Réécrivez et simplifiez : $(3 \\times 5)^2$.\n",
    "\n",
    "\n",
    "<details>\n",
    "  <summary><strong>Voir les réponses</strong></summary>\n",
    "\n",
    "  **Réponses :**\n",
    "  1. $3^4 = 81$, $7^0 = 1$, $5^{-2} = \\frac{1}{25}$.\n",
    "  2. $2^5 \\times 2^3 = 2^8 = 256$, $\\frac{6^4}{6^2} = 6^2 = 36$, $(4^2)^3 = 4^6 = 4096$.\n",
    "  3. $(3 \\times 5)^2 = 15^2 = 225$.\n",
    "  \n",
    "</details>\n",
    "\n",
    "\n",
    "---\n",
    "\n",
    "## 2. Division Euclidienne\n",
    "\n",
    "**Concept :** La division euclidienne divise un nombre $a$ par un diviseur $b$, donnant un quotient $q$ et un reste $r$ tel que \n",
    "\n",
    "$a = bq + r$ \n",
    "\n",
    "avec \n",
    "\n",
    "$0 \\leq r < b$.\n",
    "\n",
    "**Exemples :**\n",
    "\n",
    "- Diviser 20 par 3 :\n",
    "  - $20 = 3 \\times 6 + 2$\n",
    "  - Quotient : 6, Reste : 2\n",
    "\n",
    "- Diviser 50 par 7 :\n",
    "  - $50 = 7 \\times 7 + 1$\n",
    "  - Quotient : 7, Reste : 1\n",
    "\n",
    "**Applications :** \n",
    "- Calculs manuels pour vérifier des divisions.\n",
    "- Utilisation en programmation (Python) pour trouver le quotient et le reste :\n",
    "  - Quotient : `q = a // b`\n",
    "  - Reste : `r = a % b`\n",
    "  - Exemple en Python : `20 // 3` retourne 6 et `20 % 3` retourne 2.\n",
    "\n",
    "\n",
    "**Exercices :**\n",
    "1. Effectuez la division euclidienne de 38 par 5. Quel est le quotient et le reste ?\n",
    "2. Calculez le quotient et le reste de 123 par 10.\n",
    "3. Divisez 82 par 6 et trouvez le quotient et le reste.\n",
    "\n",
    "<details>\n",
    "  <summary><strong>Voir les réponses</strong></summary>\n",
    "\n",
    "  **Réponses :**\n",
    "  1. $38 = 5 \\times 7 + 3$ (Quotient = 7, Reste = 3).\n",
    "  2. $123 = 10 \\times 12 + 3$ (Quotient = 12, Reste = 3).\n",
    "  3. $82 = 6 \\times 13 + 4$ (Quotient = 13, Reste = 4).\n",
    "\n",
    "</details>\n",
    "---\n",
    "\n",
    "## 3. Numération et Bases\n",
    "\n",
    "**Bases courantes :**\n",
    "\n",
    "- **Base 2 (Binaire) :** Utilise les chiffres 0 et 1, essentiel en informatique.\n",
    "  - Exemple : $(1010)_2 = 1 \\times 2^3 + 0 \\times 2^2 + 1 \\times 2^1 + 0 \\times 2^0 = (10)_{10}$\n",
    "\n",
    "- **Base 10 (Décimale) :** Système standard utilisé dans la vie quotidienne.\n",
    "\n",
    "- **Base 16 (Hexadécimale) :** Utilise les chiffres 0-9 et les lettres A-F pour représenter 10 à 15.\n",
    "  - Exemple : $(1A)_{16} = 1 \\times 16^1 + 10 \\times 16^0 = 26$\n",
    "\n",
    "Ces bases sont essentielles pour comprendre les systèmes numériques, notamment en programmation et en électronique.\n",
    "\n",
    "\n",
    "**Exercices :**\n",
    "1. Convertissez le nombre $(1101)_2$ en base 10.\n",
    "2. Convertissez le nombre $(2A)_{16}$ en base 10.\n",
    "3. Écrivez le nombre $(45)_{10}$ en base 2.\n",
    "\n",
    "<details>\n",
    "  <summary><strong>Voir les réponses</strong></summary>\n",
    "\n",
    "  **Réponses :**\n",
    "  1. $(1101)_2 = 1 \\times 2^3 + 1 \\times 2^2 + 0 \\times 2^1 + 1 \\times 2^0 = 13$.\n",
    "  2. $(2A)_{16} = 2 \\times 16^1 + 10 \\times 16^0 = 42$.\n",
    "  3. $(45)_{10} = (101101)_2$.\n",
    "\n",
    "</details>\n",
    "\n",
    "---\n",
    "\n",
    "## 4. Conversion entre les Bases\n",
    "\n",
    "**Conversion d’une base vers le décimal :**\n",
    "\n",
    "- Multipliez chaque chiffre par sa position pondérée par la base.\n",
    "- Exemple : Convertir $(1011)_2$ en décimal :\n",
    "\n",
    "  $(1011)_2 = 1 \\times 2^3 + 0 \\times 2^2 + 1 \\times 2^1 + 1 \\times 2^0 = 8 + 0 + 2 + 1 = (11)_{10}$\n",
    "\n",
    "**Conversion du décimal vers une autre base (Méthode des divisions successives) :**\n",
    "\n",
    "1. Divisez le nombre par la base cible.\n",
    "2. Notez le reste.\n",
    "3. Continuez à diviser le quotient jusqu’à obtenir 0.\n",
    "4. Lisez les restes de bas en haut pour obtenir le nombre dans la nouvelle base.\n",
    "\n",
    "- **Exemple :** Convertir $(45)_{10}$ en base 2 :\n",
    "  - 45 ÷ 2 = 22, reste 1\n",
    "  - 22 ÷ 2 = 11, reste 0\n",
    "  - 11 ÷ 2 = 5, reste 1\n",
    "  - 5 ÷ 2 = 2, reste 1\n",
    "  - 2 ÷ 2 = 1, reste 0\n",
    "  - 1 ÷ 2 = 0, reste 1\n",
    "  - Résultat : $(101101)_2$\n",
    "\n",
    "Ces conversions sont cruciales pour la compréhension et l’utilisation des différentes bases en programmation, électronique, et calculs numériques.\n",
    "\n",
    "**Exercices :**\n",
    "1. Convertissez $(1010)_2$ en base 10.\n",
    "2. Convertissez $(37)_{10}$ en base 8.\n",
    "3. Transformez $(255)_{10}$ en base 16.\n",
    "\n",
    "<details>\n",
    "  <summary><strong>Voir les réponses</strong></summary>\n",
    "\n",
    "  **Réponses :**\n",
    "  1. $(1010)_2 = 1 \\times 2^3 + 0 \\times 2^2 + 1 \\times 2^1 + 0 \\times 2^0 = 10$.\n",
    "  2. $37 \\div 8 = 4$ reste $5$, $4 \\div 8 = 0$ reste $4$. Donc, $(37)_{10} = (45)_8$.\n",
    "  3. $255 \\div 16 = 15$ reste $15$, donc $(255)_{10} = (FF)_{16}$.\n",
    "\n",
    "</details>\n",
    "\n",
    "\n",
    "---\n",
    "\n",
    "## 5. Opérations en Binaire\n",
    "\n",
    "**Addition binaire :** Similaire à l’addition décimale, avec des retenues à 1.\n",
    "\n",
    "- **Exemple :** $(1010)_2 + (1101)_2$\n",
    "  - Alignement : \n",
    "    ```\n",
    "      1010\n",
    "    + 1101\n",
    "    ------\n",
    "     10111\n",
    "    ```\n",
    "  - Résultat : $(10111)_2$\n",
    "\n",
    "**Multiplication binaire :** Semblable à la multiplication en base 10 mais avec 0 et 1.\n",
    "\n",
    "- **Exemple :** $(101)_2 \\times (11)_2$\n",
    "  - Alignement :\n",
    "    ```\n",
    "      101\n",
    "    ×  11\n",
    "    -----\n",
    "      101\n",
    "    +1010\n",
    "    -----\n",
    "     1111\n",
    "    ```\n",
    "  - Résultat : $(1111)_2$\n",
    "  \n",
    "  \n",
    "**Exercices :**\n",
    "1. Additionnez les nombres binaires $(1011)_2$ et $(1101)_2$.\n",
    "2. Multipliez $(110)_2$ par $(11)_2$.\n",
    "3. Additionnez $(111)_2$ et $(101)_2$.\n",
    "\n",
    "<details>\n",
    "  <summary><strong>Voir les réponses</strong></summary>\n",
    "\n",
    "  **Réponses :**\n",
    "  1. $(1011)_2 + (1101)_2 = (11000)_2$.\n",
    "  2. $(110)_2 \\times (11)_2 = (10010)_2$.\n",
    "  3. $(111)_2 + $(101)_2 = (1100)_2$.\n",
    "\n",
    "</details>\n",
    "\n",
    "\n",
    "Ces opérations sont au cœur de la logique numérique, des algorithmes et des circuits digitaux.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Mise à Niveau avec Google Sheets / Excel\n",
    "\n",
    "### **1.1 Ajouter une Nouvelle Ligne**\n",
    "#### **Étapes pour Créer un Fichier Exemple :**\n",
    "1. **Ouvrir Google Sheets :**\n",
    "   - Rendez-vous sur [Google Sheets](https://sheets.google.com).\n",
    "   - Créez une nouvelle feuille de calcul.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à B4, entrez les données suivantes :\n",
    "     - A1: `Produit`\n",
    "     - B1: `Ventes`\n",
    "     - A2: `Produit A`, B2: `100`\n",
    "     - A3: `Produit B`, B3: `150`\n",
    "     - A4: `Produit C`, B4: `200`\n",
    "\n",
    "3. **Ajouter une Nouvelle Ligne :**\n",
    "   - Sélectionnez la cellule A3.\n",
    "   - Allez dans le menu **Insérer**.\n",
    "   - Cliquez sur **Ligne en dessous** pour insérer une nouvelle ligne sous la ligne 3.\n",
    "   - Entrez les données pour un nouveau produit, par exemple, A3: `Produit D`, B3: `175`.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Exemple_Ajout_Ligne` et enregistrez-le.\n",
    "\n",
    "### **1.2 Ajouter une Nouvelle Colonne**\n",
    "#### **Étapes pour Créer un Fichier Exemple :**\n",
    "1. **Ouvrir une Nouvelle Feuille de Calcul :**\n",
    "   - Créez un nouveau document Google Sheets.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à B4, entrez les données suivantes :\n",
    "     - A1: `Produit`\n",
    "     - B1: `Prix`\n",
    "     - A2: `Produit A`, B2: `10`\n",
    "     - A3: `Produit B`, B3: `15`\n",
    "     - A4: `Produit C`, B4: `20`\n",
    "\n",
    "3. **Ajouter une Nouvelle Colonne :**\n",
    "   - Sélectionnez la cellule B1.\n",
    "   - Allez dans **Insérer**.\n",
    "   - Cliquez sur **Colonne à droite** pour insérer une nouvelle colonne après `Prix`.\n",
    "   - Entrez `Quantités` dans la nouvelle colonne C1 et ajoutez des données (C2: `30`, C3: `50`, C4: `40`).\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Exemple_Ajout_Colonne` et enregistrez-le.\n",
    "\n",
    "### **1.3 Insérer Plusieurs Lignes**\n",
    "#### **Étapes pour Créer un Fichier Exemple :**\n",
    "1. **Ouvrir une Nouvelle Feuille de Calcul :**\n",
    "   - Créez un nouveau document Google Sheets.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à B6, entrez les données suivantes :\n",
    "     - A1: `Nom`\n",
    "     - B1: `Score`\n",
    "     - A2: `Alice`, B2: `85`\n",
    "     - A3: `Bob`, B3: `90`\n",
    "     - A4: `Charlie`, B4: `75`\n",
    "     - A5: `David`, B5: `80`\n",
    "     - A6: `Eve`, B6: `95`\n",
    "\n",
    "3. **Insérer Plusieurs Lignes :**\n",
    "   - Sélectionnez les lignes 4 à 6 en cliquant sur les numéros à gauche.\n",
    "   - Faites un clic droit sur la sélection et choisissez **Insérer 3 lignes au-dessus**.\n",
    "   - Entrez de nouvelles données dans les lignes insérées.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Exemple_Insertion_Multiple_Lignes` et enregistrez-le.\n",
    "\n",
    "### **1.4 Copier et Coller des Lignes ou Colonnes**\n",
    "#### **Étapes pour Créer un Fichier Exemple :**\n",
    "1. **Ouvrir une Nouvelle Feuille de Calcul :**\n",
    "   - Créez un nouveau document Google Sheets.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à C4, entrez les données suivantes :\n",
    "     - A1: `Nom`\n",
    "     - B1: `Quantité`\n",
    "     - C1: `Prix Unitaire`\n",
    "     - A2: `Produit X`, B2: `100`, C2: `10`\n",
    "     - A3: `Produit Y`, B3: `200`, C3: `20`\n",
    "     - A4: `Produit Z`, B4: `300`, C4: `30`\n",
    "\n",
    "3. **Copier et Coller une Colonne :**\n",
    "   - Sélectionnez la colonne C (de C1 à C4).\n",
    "   - Cliquez sur **Éditer > Copier** ou utilisez `Ctrl + C` (Windows) / `Cmd + C` (Mac).\n",
    "   - Sélectionnez la colonne D, puis **Éditer > Coller** ou `Ctrl + V` (Windows) / `Cmd + V` (Mac).\n",
    "   - Renommez la colonne D en `Prix Unitaire Copié`.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Exemple_Copier_Coller_Colonne` et enregistrez-le.\n",
    "\n",
    "---\n",
    "\n",
    "### **Objectif : Gérer les stocks et les ventes de la boutique du magicien qui vend des potions, des baguettes et des grimoires !**\n",
    "\n",
    "#### **Étapes pour Créer un Fichier Exemple :**\n",
    "\n",
    "1. **Ouvrir Google Sheets :**\n",
    "   - Rendez-vous sur [Google Sheets](https://sheets.google.com).\n",
    "   - Créez une nouvelle feuille de calcul.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à D4, entrez les données suivantes pour représenter les produits vendus dans la boutique :\n",
    "     - A1: `Produit`\n",
    "     - B1: `Prix Unitaire`\n",
    "     - C1: `Quantité`\n",
    "     - D1: `Ventes`\n",
    "     - A2: `Potion de Soins`, B2: `20`, C2: `50`, D2: `=B2*C2`\n",
    "     - A3: `Baguette Magique`, B3: `150`, C3: `30`, D3: `=B3*C3`\n",
    "     - A4: `Grimoire des Sortilèges`, B4: `200`, C4: `15`, D4: `=B4*C4`\n",
    "\n",
    "3. **Ajouter une Nouvelle Ligne pour un Nouveau Produit :**\n",
    "   - Le magicien a reçu un nouvel article, le `Chapeau Enchanté` ! Ajoutons-le.\n",
    "   - Sélectionnez la cellule A4.\n",
    "   - Allez dans le menu **Insérer**.\n",
    "   - Cliquez sur **Ligne en dessous** pour insérer une nouvelle ligne sous `Grimoire des Sortilèges`.\n",
    "   - Entrez les nouvelles données : A5: `Chapeau Enchanté`, B5: `100`, C5: `20`, D5: `=B5*C5`.\n",
    "\n",
    "4. **Ajouter une Nouvelle Colonne pour les Réductions :**\n",
    "   - Pour attirer plus de clients, le magicien décide d'offrir des réductions.\n",
    "   - Sélectionnez la cellule D1.\n",
    "   - Allez dans **Insérer**.\n",
    "   - Cliquez sur **Colonne à droite** pour insérer une colonne après `Ventes`.\n",
    "   - Entrez `Réduction` dans la nouvelle colonne E1, puis ajoutez les valeurs (E2: `10%`, E3: `5%`, E4: `15%`, E5: `0%`).\n",
    "\n",
    "5. **Insérer Plusieurs Lignes pour les Notes des Clients :**\n",
    "   - Sélectionnez les lignes 6 à 8 (celles sous les produits) pour insérer de l'espace pour les avis des clients enchantés.\n",
    "   - Faites un clic droit sur la sélection et choisissez **Insérer 3 lignes au-dessus**.\n",
    "   - Ajoutez des notes dans les lignes insérées, par exemple :\n",
    "     - A6: `Note : La Potion de Soins a un effet rapide !`\n",
    "     - A7: `Note : La Baguette Magique est la préférée des apprentis.`\n",
    "     - A8: `Note : Le Grimoire est rare et précieux.`\n",
    "\n",
    "6. **Copier et Coller une Colonne pour Calculer les Totaux Réels après Réduction :**\n",
    "   - Le magicien veut calculer combien il gagne vraiment après les réductions.\n",
    "   - Sélectionnez la colonne D (de D1 à D5).\n",
    "   - Cliquez sur **Éditer > Copier** ou utilisez `Ctrl + C` (Windows) / `Cmd + C` (Mac).\n",
    "   - Sélectionnez la colonne F, puis **Éditer > Coller** ou `Ctrl + V` (Windows) / `Cmd + V` (Mac).\n",
    "   - Renommez la colonne F en `Total après Réduction`.\n",
    "   - Ajustez les formules pour tenir compte des réductions (ex. F2: `=D2*(1-VAL(E2))`).\n",
    "\n",
    "7. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Gestion_Boutique_Magicien` et enregistrez-le.\n",
    "\n",
    "### **Résumé :**\n",
    "Avec cet exemple, vous avez appris à :\n",
    "- Ajouter de nouvelles lignes et colonnes pour gérer les produits de la boutique magique.\n",
    "- Insérer plusieurs lignes pour des commentaires personnalisés.\n",
    "- Copier et coller des colonnes pour calculer les ventes ajustées.\n",
    "- Créer un environnement interactif qui rappelle les défis réels d'une gestion de boutique… même enchantée !\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "\n",
    "### Gérer l'inventaire des ingrédients pour un restaurant\n",
    "\n",
    "#### **Étapes pour Créer le Fichier : \"Gestion_Inventaire_Restaurant\"**\n",
    "\n",
    "1. **Ouvrir Google Sheets :**\n",
    "   - Rendez-vous sur [Google Sheets](https://sheets.google.com) et créez une nouvelle feuille de calcul.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à D4, entrez les données pour représenter les stocks de votre restaurant :\n",
    "     - A1: `Ingrédient`\n",
    "     - B1: `Quantité en Stock`\n",
    "     - C1: `Prix par Unité (€)`\n",
    "     - D1: `Fournisseur`\n",
    "     - A2: `Tomates`, B2: `50`, C2: `2`, D2: `Primeur Local`\n",
    "     - A3: `Poulet`, B3: `30`, C3: `6`, D3: `Boucherie Fine`\n",
    "     - A4: `Laitue`, B4: `20`, C4: `1.5`, D4: `Primeur Local`\n",
    "\n",
    "#### **1. Supprimer des Lignes ou Colonnes**\n",
    "\n",
    "3. **Supprimer une Colonne :**\n",
    "   - Après une analyse, vous décidez de retirer la colonne des `Fournisseurs` car elle est peu utilisée dans les rapports quotidiens.\n",
    "   - Sélectionnez la colonne D en cliquant sur la lettre `D`.\n",
    "   - Faites un clic droit sur la sélection, puis cliquez sur **Supprimer la colonne**.\n",
    "\n",
    "4. **Supprimer une Ligne :**\n",
    "   - Le restaurant décide de retirer temporairement les plats contenant de la laitue du menu en raison de problèmes d'approvisionnement.\n",
    "   - Sélectionnez la ligne 4 en cliquant sur le numéro `4`.\n",
    "   - Faites un clic droit sur la sélection, puis cliquez sur **Supprimer la ligne**.\n",
    "\n",
    "5. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Inventaire_Supprimer_Lignes_Colonnes` et enregistrez-le.\n",
    "\n",
    "#### **2. Effacer les Valeurs tout en Conservant le Formatage**\n",
    "\n",
    "6. **Appliquer du Formatage :**\n",
    "   - Sélectionnez les cellules B2 à C4 et appliquez un format monétaire à la colonne C pour clarifier les prix.\n",
    "   - Ajoutez une mise en forme conditionnelle pour mettre en rouge les quantités inférieures à 20 (signe d’un stock bas).\n",
    "\n",
    "7. **Effacer les Valeurs :**\n",
    "   - Vous devez réinitialiser les quantités en stock pour effectuer un nouvel inventaire à la fin du mois.\n",
    "   - Sélectionnez les cellules B2 à B3.\n",
    "   - Allez dans **Éditer > Supprimer les valeurs** ou appuyez sur `Suppr` (Windows) / `Delete` (Mac).\n",
    "   - Le formatage reste en place, prêt pour les nouvelles entrées d'inventaire.\n",
    "\n",
    "8. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Inventaire_Effacer_Valeurs` et enregistrez-le.\n",
    "\n",
    "#### **3. Couper des Données et les Coller Ailleurs**\n",
    "\n",
    "9. **Couper les Données :**\n",
    "   - Le restaurant décide de réorganiser ses stocks, en plaçant les ingrédients principaux en haut de la liste pour faciliter la gestion.\n",
    "   - Sélectionnez les cellules A3 à C3 (`Poulet`).\n",
    "   - Faites un clic droit sur la sélection et choisissez **Couper** ou utilisez `Ctrl + X` (Windows) / `Cmd + X` (Mac).\n",
    "\n",
    "10. **Coller les Données Ailleurs :**\n",
    "    - Sélectionnez la ligne 2 en cliquant sur le numéro `2` pour placer le poulet juste après les tomates.\n",
    "    - Faites un clic droit et sélectionnez **Coller** ou utilisez `Ctrl + V` (Windows) / `Cmd + V` (Mac).\n",
    "    - Les données du poulet sont maintenant réorganisées en fonction de leur priorité dans le menu.\n",
    "\n",
    "11. **Sauvegarder le Fichier :**\n",
    "    - Nommez le fichier `Inventaire_Couper_Coller` et enregistrez-le.\n",
    "\n",
    "### **2.2 Masquer des Colonnes ou des Lignes**\n",
    "\n",
    "#### **Masquer des Colonnes**\n",
    "\n",
    "12. **Masquer une Colonne :**\n",
    "    - Vous souhaitez masquer la colonne des prix pendant que vous réorganisez les quantités pour éviter les erreurs de manipulation.\n",
    "    - Sélectionnez la colonne C en cliquant sur la lettre `C`.\n",
    "    - Faites un clic droit et sélectionnez **Masquer la colonne**.\n",
    "    - La colonne des prix est masquée, sécurisant les données sensibles pendant les ajustements.\n",
    "\n",
    "13. **Sauvegarder le Fichier :**\n",
    "    - Nommez le fichier `Inventaire_Masquer_Colonnes` et enregistrez-le.\n",
    "\n",
    "#### **Masquer des Lignes**\n",
    "\n",
    "14. **Masquer une Ligne :**\n",
    "    - Pour effectuer une vérification de qualité, vous masquez les ingrédients qui ne sont pas disponibles cette semaine.\n",
    "    - Sélectionnez la ligne 3 (`Poulet`) en cliquant sur le numéro `3`.\n",
    "    - Faites un clic droit et sélectionnez **Masquer la ligne**.\n",
    "    - La ligne du poulet est masquée jusqu’à ce qu’il soit de nouveau disponible.\n",
    "\n",
    "15. **Sauvegarder le Fichier :**\n",
    "    - Nommez le fichier `Inventaire_Masquer_Lignes` et enregistrez-le.\n",
    "\n",
    "### **Résumé :**\n",
    "Avec cet exemple, vous avez appris à :\n",
    "- Supprimer des lignes et colonnes non nécessaires pour simplifier la gestion de l’inventaire.\n",
    "- Effacer des valeurs tout en maintenant le formatage pour des réinitialisations rapides.\n",
    "- Déplacer des articles dans l’inventaire pour refléter leur importance dans les opérations du restaurant.\n",
    "- Masquer des informations temporaires pour éviter les confusions lors des ajustements.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Gestion des Ventes d'un Petit Commerce\n",
    "\n",
    "#### **Objectif : Calculer les totaux, les moyennes, et gérer les calculs dynamiques pour un commerce vendant des articles courants (ex: café, sandwichs, desserts).**\n",
    "\n",
    "#### **Étapes pour Créer le Fichier : \"Gestion_Ventes_Commerce\"**\n",
    "\n",
    "1. **Ouvrir Google Sheets :**\n",
    "   - Rendez-vous sur [Google Sheets](https://sheets.google.com) et créez une nouvelle feuille de calcul.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à B6, entrez les données suivantes pour représenter les ventes quotidiennes :\n",
    "     - A1: `Produit`\n",
    "     - B1: `Ventes du Jour (€)`\n",
    "     - A2: `Café`, B2: `10`\n",
    "     - A3: `Sandwich`, B3: `20`\n",
    "     - A4: `Dessert`, B4: `30`\n",
    "     - A5: `Boisson`, B5: `40`\n",
    "     - A6: `Snack`, B6: `50`\n",
    "\n",
    "#### **1. Calculer une Somme**\n",
    "\n",
    "3. **Calculer la Somme des Ventes :**\n",
    "   - Sélectionnez la cellule B7.\n",
    "   - Tapez la formule `=SOMME(B2:B6)` et appuyez sur **Entrée**.\n",
    "   - La cellule B7 affichera le total des ventes du jour (`150 €`).\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Ventes_Total_Somme` et enregistrez-le.\n",
    "\n",
    "#### **2. Calculer une Moyenne**\n",
    "\n",
    "5. **Calculer la Moyenne des Ventes :**\n",
    "   - Sélectionnez la cellule B8.\n",
    "   - Tapez la formule `=MOYENNE(B2:B6)` et appuyez sur **Entrée**.\n",
    "   - La cellule B8 affichera la moyenne des ventes par produit (`30 €`).\n",
    "\n",
    "6. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Ventes_Moyenne` et enregistrez-le.\n",
    "\n",
    "### **3. Créer une Série de Nombres avec le Remplissage Automatique**\n",
    "\n",
    "#### **Utiliser Auto-fill pour Générer des Dates de Vente**\n",
    "\n",
    "7. **Générer une Série de Dates :**\n",
    "   - Dans la cellule C1, entrez `Date`.\n",
    "   - Dans C2, entrez `01/09/2024`.\n",
    "   - Dans C3, entrez `02/09/2024`.\n",
    "\n",
    "8. **Utiliser Auto-fill pour Compléter les Dates :**\n",
    "   - Sélectionnez les cellules C2 et C3.\n",
    "   - Placez le curseur en bas à droite de la cellule C3 jusqu'à voir une petite croix noire (le carré de remplissage).\n",
    "   - Cliquez et faites glisser le carré de remplissage vers le bas jusqu'à C10.\n",
    "   - Les cellules se rempliront automatiquement avec les dates jusqu’au 10 septembre.\n",
    "\n",
    "9. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Dates_Série_Auto_Fill` et enregistrez-le.\n",
    "\n",
    "### **4. Calculs Dynamiques avec Références de Cellules**\n",
    "\n",
    "#### **Références Relatives pour des Calculs Ajustables**\n",
    "\n",
    "10. **Calculer les Ventes Ajustées avec une Référence Relative :**\n",
    "    - Ajoutez une colonne D avec l'en-tête `Ventes Ajustées`.\n",
    "    - Dans D2, tapez `=B2 * 1.1` pour ajouter une augmentation de 10% (par exemple, pour une promotion spéciale).\n",
    "    - Appuyez sur **Entrée** pour afficher le résultat (`11 €` pour le café).\n",
    "    - Copiez la formule de D2 en faisant glisser le carré de remplissage vers le bas jusqu'à D6.\n",
    "    - Les ventes ajustées s’ajusteront automatiquement pour chaque produit.\n",
    "\n",
    "11. **Sauvegarder le Fichier :**\n",
    "    - Nommez le fichier `Ventes_Adjustées_Relatives` et enregistrez-le.\n",
    "\n",
    "#### **Références Absolues pour Fixer un Taux de Réduction**\n",
    "\n",
    "12. **Calculer les Réductions avec une Référence Absolue :**\n",
    "    - Dans la cellule E1, entrez `Réduction (%)`.\n",
    "    - Dans E2, entrez `10`.\n",
    "    - Dans la colonne F, ajoutez l'en-tête `Ventes après Réduction`.\n",
    "    - Dans F2, tapez `=B2 * (1 - $E$2/100)` pour appliquer une réduction de 10%.\n",
    "    - Appuyez sur **Entrée** pour voir le résultat (`9 €` pour le café après réduction).\n",
    "    - Copiez la formule de F2 vers le bas jusqu’à F6.\n",
    "    - Grâce à la référence absolue `$E$2`, toutes les cellules appliqueront la même réduction.\n",
    "\n",
    "13. **Sauvegarder le Fichier :**\n",
    "    - Nommez le fichier `Ventes_Réductions_Absolues` et enregistrez-le.\n",
    "\n",
    "### **Résumé :**\n",
    "Cet exemple montre comment :\n",
    "- Calculer facilement les totaux et moyennes des ventes pour un commerce.\n",
    "- Générer des séries automatiques comme des dates pour le suivi des ventes.\n",
    "- Utiliser des références dynamiques pour ajuster des calculs selon les besoins quotidiens (promotions, ajustements).\n",
    "- Appliquer des réductions ou ajustements fixes avec des références absolues pour des opérations précises.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### **Exemple Unique Réaliste : Gestion des Produits d'un Magasin de Vêtements**\n",
    "\n",
    "#### **Objectif : Trier et filtrer les données de ventes, valider les entrées et formater les cellules pour mieux gérer les stocks et les ventes dans un magasin de vêtements.**\n",
    "\n",
    "#### **Étapes pour Créer le Fichier : \"Gestion_Produits_Vêtements\"**\n",
    "\n",
    "1. **Ouvrir Google Sheets :**\n",
    "   - Rendez-vous sur [Google Sheets](https://sheets.google.com) et créez une nouvelle feuille de calcul.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à B6, entrez les données suivantes pour représenter les ventes de différents produits :\n",
    "     - A1: `Produit`\n",
    "     - B1: `Ventes`\n",
    "     - A2: `T-shirt`, B2: `50`\n",
    "     - A3: `Jeans`, B3: `30`\n",
    "     - A4: `Jacket`, B4: `70`\n",
    "     - A5: `Chapeau`, B5: `20`\n",
    "     - A6: `Écharpe`, B6: `60`\n",
    "\n",
    "#### **1. Trier les Données en Ordre Croissant/Décroissant**\n",
    "\n",
    "3. **Trier les Ventes :**\n",
    "   - Sélectionnez les cellules A1 à B6.\n",
    "   - Allez dans **Données > Trier la plage**.\n",
    "   - Choisissez `Trier par Ventes` et sélectionnez **Ordre croissant** pour voir les produits qui se vendent le moins, ou **Ordre décroissant** pour voir les meilleures ventes.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Produits_Trier_Ventes` et enregistrez-le.\n",
    "\n",
    "#### **2. Filtrer les Données pour une Analyse Rapide**\n",
    "\n",
    "5. **Appliquer un Filtre :**\n",
    "   - Sélectionnez la ligne 1 (A1 à B1).\n",
    "   - Cliquez sur **Données > Créer un filtre**.\n",
    "   - Cliquez sur l'icône de filtre dans la cellule B1.\n",
    "   - Choisissez **Filtrer par condition > Supérieur à 40** pour n’afficher que les produits avec des ventes supérieures à 40.\n",
    "\n",
    "6. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Produits_Filtrer_Ventes` et enregistrez-le.\n",
    "\n",
    "### **4.2 Créer des Validations de Données pour Éviter les Erreurs de Saisie**\n",
    "\n",
    "#### **Créer des Listes Déroulantes pour Catégoriser les Produits**\n",
    "\n",
    "7. **Créer une Liste Déroulante :**\n",
    "   - Dans la colonne C, entrez des catégories de produits :\n",
    "     - C1: `Catégories`\n",
    "     - C2: `T-shirt`\n",
    "     - C3: `Jeans`\n",
    "     - C4: `Accessoires`\n",
    "\n",
    "8. **Créer une Liste Déroulante pour les Ventes :**\n",
    "   - Sélectionnez la cellule D1 et tapez `Type de Produit`.\n",
    "   - Allez dans **Données > Validation de données**.\n",
    "   - Choisissez **Liste d’éléments** et entrez les options : `T-shirt, Jeans, Accessoires`.\n",
    "   - Cliquez sur **Enregistrer**.\n",
    "   - La cellule D1 contiendra maintenant une liste déroulante pour sélectionner le type de produit.\n",
    "\n",
    "9. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Validation_Liste_Déroulante` et enregistrez-le.\n",
    "\n",
    "#### **Restreindre les Entrées à des Valeurs Numériques pour les Stocks**\n",
    "\n",
    "10. **Appliquer une Validation Numérique :**\n",
    "    - Sélectionnez les cellules E2 à E6, où les quantités de stock seront saisies.\n",
    "    - Allez dans **Données > Validation de données**.\n",
    "    - Définissez la condition sur **Nombre > Supérieur à 0** pour s'assurer que seules des valeurs valides sont saisies.\n",
    "    - Cliquez sur **Enregistrer**. Les cellules accepteront uniquement des valeurs positives.\n",
    "\n",
    "11. **Sauvegarder le Fichier :**\n",
    "    - Nommez le fichier `Validation_Entrées_Numériques` et enregistrez-le.\n",
    "\n",
    "### **4.3 Fusionner et Formater des Cellules pour une Meilleure Présentation**\n",
    "\n",
    "#### **Fusionner des Cellules pour Créer des En-têtes de Tableau**\n",
    "\n",
    "12. **Créer un En-tête Fusionné :**\n",
    "    - Dans la cellule G1, tapez `Rapport de Ventes Hebdomadaire`.\n",
    "    - Sélectionnez G1 et H1.\n",
    "    - Allez dans **Format > Fusionner les cellules > Fusionner horizontalement** pour créer un en-tête stylisé.\n",
    "\n",
    "13. **Sauvegarder le Fichier :**\n",
    "    - Nommez le fichier `Fusionner_En-têtes` et enregistrez-le.\n",
    "\n",
    "#### **Utiliser des Séparateurs de Milliers et la Mise en Forme Conditionnelle**\n",
    "\n",
    "14. **Formater les Montants des Ventes :**\n",
    "    - Dans les cellules J1 à J4, entrez des montants de ventes :\n",
    "      - J1: `Ventes Totales`\n",
    "      - J2: `1000`\n",
    "      - J3: `1500`\n",
    "      - J4: `2500`\n",
    "\n",
    "15. **Appliquer un Séparateur de Milliers :**\n",
    "    - Sélectionnez les cellules J2 à J4.\n",
    "    - Allez dans **Format > Nombre > Nombre avec séparateur de milliers**. Les valeurs apparaîtront avec des virgules, facilitant la lecture.\n",
    "\n",
    "16. **Ajouter une Mise en Forme Conditionnelle pour Identifier les Meilleures Ventes :**\n",
    "    - Sélectionnez les cellules J2 à J4.\n",
    "    - Allez dans **Format > Mise en forme conditionnelle**.\n",
    "    - Ajoutez une règle pour colorer en vert les valeurs supérieures à 1500 pour mettre en évidence les meilleures ventes.\n",
    "\n",
    "17. **Sauvegarder le Fichier :**\n",
    "    - Nommez le fichier `Séparateurs_Conditionnel` et enregistrez-le.\n",
    "\n",
    "### **Résumé :**\n",
    "Avec cet exemple, vous avez appris à :\n",
    "- Trier et filtrer vos données de vente pour obtenir une vue d'ensemble rapide et ciblée.\n",
    "- Créer des listes déroulantes et valider les données pour éviter les erreurs de saisie et maintenir l'exactitude.\n",
    "- Fusionner et formater des cellules pour améliorer la présentation et l'accessibilité des informations dans vos rapports.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### **Exemple : Suivi du Budget Personnel**\n",
    "\n",
    "#### **Objectif : Gérer vos finances personnelles en utilisant des fonctions pour suivre les revenus, les dépenses, et planifier l'épargne.**\n",
    "\n",
    "#### **Étapes pour Créer le Fichier : \"Budget_Personnel\"**\n",
    "\n",
    "1. **Ouvrir Google Sheets :**\n",
    "   - Rendez-vous sur [Google Sheets](https://sheets.google.com) et créez une nouvelle feuille de calcul.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à D8, entrez les données suivantes pour créer un tableau de suivi des revenus et des dépenses :\n",
    "     - A1: `Catégorie`\n",
    "     - B1: `Montant (€)`\n",
    "     - A2: `Salaire`, B2: `2000`\n",
    "     - A3: `Freelance`, B3: `500`\n",
    "     - A4: `Loyer`, B4: `-700`\n",
    "     - A5: `Courses`, B5: `-300`\n",
    "     - A6: `Divertissement`, B6: `-150`\n",
    "     - A7: `Transport`, B7: `-100`\n",
    "     - A8: `Épargne`, B8: `300`\n",
    "\n",
    "#### **1. Calculer le Total des Revenus et Dépenses**\n",
    "\n",
    "3. **Calculer le Solde :**\n",
    "   - Sélectionnez la cellule B9.\n",
    "   - Tapez la formule `=SOMME(B2:B8)` pour calculer le solde total du budget.\n",
    "   - La cellule B9 affichera le total (`1550 €`).\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Budget_Total` et enregistrez-le.\n",
    "\n",
    "#### **2. Utiliser des Graphiques pour Visualiser les Dépenses**\n",
    "\n",
    "5. **Créer un Graphique à Secteurs :**\n",
    "   - Sélectionnez les cellules A2 à B8 pour visualiser les catégories et leurs montants.\n",
    "   - Cliquez sur **Insérer > Graphique**.\n",
    "   - Choisissez le type **Graphique à Secteurs** pour voir la répartition des revenus et des dépenses.\n",
    "   - Ajustez le graphique pour ajouter des titres et des étiquettes de pourcentages.\n",
    "\n",
    "6. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Budget_Graphique` et enregistrez-le.\n",
    "\n",
    "#### **3. Gérer les Erreurs avec SIERREUR pour des Calculs Sensibles**\n",
    "\n",
    "7. **Gérer les Erreurs dans les Calculs d’Épargne :**\n",
    "   - Dans la cellule B10, tapez `=SIERREUR(B2 + B3 - (B4 + B5 + B6 + B7); \"Erreur de calcul\")` pour calculer l’épargne nette.\n",
    "   - Cette formule affichera un message d'erreur personnalisé si des valeurs sont manquantes ou incorrectes.\n",
    "\n",
    "8. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Budget_SIERREUR` et enregistrez-le.\n",
    "\n",
    "### **Résumé :**\n",
    "Avec cet exemple de gestion des finances personnelles, vous avez appris à :\n",
    "- Suivre vos revenus et dépenses.\n",
    "- Utiliser des graphiques pour visualiser vos finances.\n",
    "- Gérer les erreurs dans les calculs pour maintenir l'exactitude.\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### **Exemple Réaliste : Gestion des Stocks dans un Entreposage Logistique**\n",
    "\n",
    "#### **Objectif : Utiliser des fonctions avancées pour gérer les stocks, suivre les entrées et sorties des produits, et optimiser l'inventaire dans un entrepôt logistique.**\n",
    "\n",
    "#### **Étapes pour Créer le Fichier : \"Gestion_Stocks_Entrepôt\"**\n",
    "\n",
    "1. **Ouvrir Google Sheets :**\n",
    "   - Rendez-vous sur [Google Sheets](https://sheets.google.com) et créez une nouvelle feuille de calcul.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à D10, entrez les données suivantes représentant les stocks de produits :\n",
    "     - A1: `Produit`\n",
    "     - B1: `Quantité Initiale`\n",
    "     - C1: `Entrées`\n",
    "     - D1: `Sorties`\n",
    "     - A2: `Produit A`, B2: `100`, C2: `20`, D2: `10`\n",
    "     - A3: `Produit B`, B3: `150`, C3: `30`, D3: `25`\n",
    "     - A4: `Produit C`, B4: `200`, C4: `50`, D4: `40`\n",
    "     - A5: `Produit D`, B5: `80`, C5: `10`, D5: `5`\n",
    "     - A6: `Produit E`, B6: `60`, C6: `15`, D6: `10`\n",
    "\n",
    "#### **1. Calculer les Stocks Restants**\n",
    "\n",
    "3. **Calculer les Stocks Restants :**\n",
    "   - Ajoutez une colonne E intitulée `Stock Restant`.\n",
    "   - Dans la cellule E2, tapez la formule `=B2 + C2 - D2` pour calculer le stock restant du produit A.\n",
    "   - Copiez cette formule vers le bas jusqu'à E6 pour tous les produits.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Exemple_Gestion_Stocks_Restants` et enregistrez-le.\n",
    "\n",
    "#### **2. Utiliser des Alertes pour les Stocks Critiques avec Mise en Forme Conditionnelle**\n",
    "\n",
    "5. **Appliquer une Mise en Forme Conditionnelle pour Alerter sur les Stocks Bas :**\n",
    "   - Sélectionnez les cellules E2 à E6.\n",
    "   - Allez dans **Format > Mise en forme conditionnelle**.\n",
    "   - Définissez une règle pour colorer les cellules en rouge si les stocks restants sont inférieurs à 20.\n",
    "   - Cliquez sur **Terminé** pour appliquer la mise en forme.\n",
    "\n",
    "6. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Exemple_Alertes_Stocks_Bas` et enregistrez-le.\n",
    "\n",
    "#### **3. Suivre les Mouvements de Stock par Date avec un Tableau Croisé Dynamique**\n",
    "\n",
    "7. **Créer un Journal des Mouvements de Stock :**\n",
    "   - Ajoutez une nouvelle feuille nommée `Journal`.\n",
    "   - Dans les cellules A1 à D10, entrez les mouvements de stock :\n",
    "     - A1: `Date`\n",
    "     - B1: `Produit`\n",
    "     - C1: `Type` (Entrée/Sortie)\n",
    "     - D1: `Quantité`\n",
    "     - A2: `01/09/2024`, B2: `Produit A`, C2: `Entrée`, D2: `20`\n",
    "     - A3: `01/09/2024`, B3: `Produit B`, C3: `Sortie`, D3: `10`\n",
    "     - A4: `02/09/2024`, B4: `Produit C`, C4: `Entrée`, D4: `30`\n",
    "     - A5: `03/09/2024`, B5: `Produit A`, C5: `Sortie`, D5: `15`\n",
    "     - A6: `03/09/2024`, B6: `Produit D`, C6: `Entrée`, D6: `5`\n",
    "\n",
    "8. **Créer un Tableau Croisé Dynamique pour Suivre les Mouvements :**\n",
    "   - Sélectionnez toutes les données du journal.\n",
    "   - Allez dans **Données > Tableau croisé dynamique**.\n",
    "   - Dans l'éditeur de tableau croisé dynamique, glissez `Produit` dans les **Lignes** et `Quantité` dans les **Valeurs**.\n",
    "   - Utilisez `Type` pour différencier les entrées et sorties.\n",
    "\n",
    "9. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Exemple_Tableau_Croisé_Dynamique_Stock` et enregistrez-le.\n",
    "\n",
    "#### **4. Consolider les Stocks de Plusieurs Entrepôts**\n",
    "\n",
    "10. **Créer des Feuilles pour Chaque Entrepôt :**\n",
    "    - Ajoutez des feuilles nommées `Entrepôt 1`, `Entrepôt 2`, et `Entrepôt 3`.\n",
    "\n",
    "11. **Entrer les Données de Stock dans Chaque Entrepôt :**\n",
    "    - **Feuille \"Entrepôt 1\" :**\n",
    "      - A1: `Produit`\n",
    "      - B1: `Stock`\n",
    "      - A2: `Produit A`, B2: `50`\n",
    "      - A3: `Produit B`, B3: `30`\n",
    "   \n",
    "    - **Feuille \"Entrepôt 2\" :**\n",
    "      - A1: `Produit`\n",
    "      - B1: `Stock`\n",
    "      - A2: `Produit A`, B2: `60`\n",
    "      - A3: `Produit B`, B3: `20`\n",
    "   \n",
    "    - **Feuille \"Entrepôt 3\" :**\n",
    "      - A1: `Produit`\n",
    "      - B1: `Stock`\n",
    "      - A2: `Produit A`, B2: `40`\n",
    "      - A3: `Produit B`, B3: `25`\n",
    "\n",
    "12. **Créer une Feuille de Consolidation :**\n",
    "    - Ajoutez une nouvelle feuille nommée `Consolidation`.\n",
    "    - Dans cette feuille, entrez :\n",
    "      - A1: `Produit`\n",
    "      - B1: `Stock Total`\n",
    "\n",
    "13. **Consolider les Stocks :**\n",
    "    - Dans la cellule B2, tapez la formule `=SOMME(Entrepôt 1!B2; Entrepôt 2!B2; Entrepôt 3!B2)` pour consolider les stocks du Produit A.\n",
    "    - Répétez pour les autres produits.\n",
    "\n",
    "14. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Exemple_Consolidation_Stocks_Entrepôts` et enregistrez-le.\n",
    "\n",
    "### **Résumé :**\n",
    "Avec cet exemple, vous avez appris à :\n",
    "- Suivre les entrées et sorties de stock et calculer les stocks restants.\n",
    "- Mettre en place des alertes visuelles pour les stocks bas.\n",
    "- Créer des tableaux croisés dynamiques pour suivre les mouvements de stock.\n",
    "- Consolider les données de plusieurs entrepôts pour une vue globale.\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### **7.1 Créer un Graphique à Colonnes pour Comparer des Valeurs**\n",
    "\n",
    "#### **Exemple Pratique : Comparer les Ventes Mensuelles d'un Magasin de Vêtements**\n",
    "\n",
    "##### **Étapes pour Créer un Fichier Exemple :**\n",
    "\n",
    "1. **Ouvrir Google Sheets :**\n",
    "   - Rendez-vous sur [Google Sheets](https://sheets.google.com) et créez une nouvelle feuille de calcul.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à B5, entrez les données suivantes pour suivre les ventes des derniers mois :\n",
    "     - A1: `Mois`\n",
    "     - B1: `Ventes (€)`\n",
    "     - A2: `Janvier`, B2: `12000`\n",
    "     - A3: `Février`, B3: `15000`\n",
    "     - A4: `Mars`, B4: `13000`\n",
    "     - A5: `Avril`, B5: `17000`\n",
    "\n",
    "3. **Créer un Graphique à Colonnes :**\n",
    "   - Sélectionnez les cellules A1 à B5.\n",
    "   - Cliquez sur **Insérer > Graphique**.\n",
    "   - Dans l'éditeur de graphique, sélectionnez le type **Colonnes** pour comparer visuellement les ventes par mois.\n",
    "   - Personnalisez le graphique en ajoutant un titre : **\"Ventes Mensuelles du Magasin\"**.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Graphique_Ventes_Colonnes` et enregistrez-le.\n",
    "\n",
    "### **7.2 Tracer des Graphiques Linéaires pour Suivre les Tendances**\n",
    "\n",
    "#### **Exemple Pratique : Suivre l’Évolution des Températures sur une Semaine**\n",
    "\n",
    "##### **Étapes pour Créer un Fichier Exemple :**\n",
    "\n",
    "1. **Créer une Nouvelle Feuille de Calcul :**\n",
    "   - Créez un nouveau document Google Sheets.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à B8, entrez les données suivantes pour suivre les températures sur une semaine :\n",
    "     - A1: `Jour`\n",
    "     - B1: `Température (°C)`\n",
    "     - A2: `Lundi`, B2: `15`\n",
    "     - A3: `Mardi`, B3: `17`\n",
    "     - A4: `Mercredi`, B4: `19`\n",
    "     - A5: `Jeudi`, B5: `21`\n",
    "     - A6: `Vendredi`, B6: `20`\n",
    "     - A7: `Samedi`, B7: `22`\n",
    "     - A8: `Dimanche`, B8: `18`\n",
    "\n",
    "3. **Créer un Graphique Linéaire :**\n",
    "   - Sélectionnez les cellules A1 à B8.\n",
    "   - Cliquez sur **Insérer > Graphique**.\n",
    "   - Choisissez le type **Linéaire** pour représenter l’évolution des températures.\n",
    "   - Ajoutez un titre : **\"Évolution des Températures sur une Semaine\"**.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Graphique_Tendances_Températures` et enregistrez-le.\n",
    "\n",
    "### **7.3 Créer des Graphiques à Secteurs pour Montrer des Parts de Marché**\n",
    "\n",
    "#### **Exemple Pratique : Répartition des Parts de Marché des Principaux Constructeurs Auto**\n",
    "\n",
    "##### **Étapes pour Créer un Fichier Exemple :**\n",
    "\n",
    "1. **Créer une Nouvelle Feuille de Calcul :**\n",
    "   - Créez un nouveau document Google Sheets.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à B6, entrez les parts de marché des principaux constructeurs automobiles :\n",
    "     - A1: `Constructeur`\n",
    "     - B1: `Part de Marché (%)`\n",
    "     - A2: `Toyota`, B2: `25`\n",
    "     - A3: `Volkswagen`, B3: `20`\n",
    "     - A4: `Ford`, B4: `15`\n",
    "     - A5: `Honda`, B5: `10`\n",
    "     - A6: `BMW`, B6: `30`\n",
    "\n",
    "3. **Créer un Graphique à Secteurs :**\n",
    "   - Sélectionnez les cellules A1 à B6.\n",
    "   - Cliquez sur **Insérer > Graphique**.\n",
    "   - Choisissez le type **Secteurs** pour visualiser la répartition des parts de marché.\n",
    "   - Ajoutez des étiquettes de pourcentage pour chaque segment et un titre : **\"Parts de Marché des Constructeurs Auto\"**.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Graphique_Secteurs_Marché` et enregistrez-le.\n",
    "\n",
    "### **7.4 Utiliser des Nuages de Points pour Examiner des Corrélations**\n",
    "\n",
    "#### **Exemple Pratique : Relation Entre Temps d'Étude et Notes des Étudiants**\n",
    "\n",
    "##### **Étapes pour Créer un Fichier Exemple :**\n",
    "\n",
    "1. **Créer une Nouvelle Feuille de Calcul :**\n",
    "   - Créez un nouveau document Google Sheets.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à B6, entrez les données pour observer la corrélation entre le temps d’étude et les notes obtenues :\n",
    "     - A1: `Heures d'Étude`\n",
    "     - B1: `Note`\n",
    "     - A2: `1`, B2: `60`\n",
    "     - A3: `2`, B3: `70`\n",
    "     - A4: `3`, B4: `75`\n",
    "     - A5: `4`, B5: `80`\n",
    "     - A6: `5`, B6: `90`\n",
    "\n",
    "3. **Créer un Nuage de Points :**\n",
    "   - Sélectionnez les cellules A1 à B6.\n",
    "   - Cliquez sur **Insérer > Graphique**.\n",
    "   - Choisissez le type **Nuage de Points** pour visualiser la relation.\n",
    "   - Ajoutez une ligne de tendance pour mettre en évidence la corrélation et un titre : **\"Corrélation Temps d'Étude vs. Notes\"**.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Graphique_Corrélation_Étude_Notes` et enregistrez-le.\n",
    "\n",
    "### **7.5 Tracer des Graphiques en Aires pour Visualiser l'Accumulation**\n",
    "\n",
    "#### **Exemple Pratique : Visualiser l’Accroissement des Ventes Cumulées par Trimestre**\n",
    "\n",
    "##### **Étapes pour Créer un Fichier Exemple :**\n",
    "\n",
    "1. **Créer une Nouvelle Feuille de Calcul :**\n",
    "   - Créez un nouveau document Google Sheets.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à B5, entrez les ventes cumulées par trimestre :\n",
    "     - A1: `Trimestre`\n",
    "     - B1: `Ventes Cumulées (€)`\n",
    "     - A2: `Q1`, B2: `8000`\n",
    "     - A3: `Q2`, B3: `15000`\n",
    "     - A4: `Q3`, B4: `23000`\n",
    "     - A5: `Q4`, B5: `30000`\n",
    "\n",
    "3. **Créer un Graphique en Aires :**\n",
    "   - Sélectionnez les cellules A1 à B5.\n",
    "   - Cliquez sur **Insérer > Graphique**.\n",
    "   - Choisissez le type **Aires** pour montrer l’évolution des ventes cumulées.\n",
    "   - Ajoutez un titre : **\"Ventes Cumulées par Trimestre\"**.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Graphique_Aires_Ventes_Cumulées` et enregistrez-le.\n",
    "\n",
    "### **7.6 Utiliser des Histogrammes pour Analyser la Distribution des Fréquences**\n",
    "\n",
    "#### **Exemple Pratique : Distribution des Notes des Étudiants dans un Examen**\n",
    "\n",
    "##### **Étapes pour Créer un Fichier Exemple :**\n",
    "\n",
    "1. **Créer une Nouvelle Feuille de Calcul :**\n",
    "   - Créez un nouveau document Google Sheets.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à A11, entrez les notes des étudiants pour analyser la distribution :\n",
    "     - A1: `Notes`\n",
    "     - A2: `45`\n",
    "     - A3: `55`\n",
    "     - A4: `60`\n",
    "     - A5: `70`\n",
    "     - A6: `75`\n",
    "     - A7: `80`\n",
    "     - A8: `85`\n",
    "     - A9: `90`\n",
    "     - A10: `95`\n",
    "     - A11: `100`\n",
    "\n",
    "3. **Créer un Histogramme :**\n",
    "   - Sélectionnez les cellules A1 à A11.\n",
    "   - Cliquez sur **Insérer > Graphique**.\n",
    "   - Choisissez le type **Histogramme** pour analyser la répartition des notes.\n",
    "   - Ajoutez un titre : **\"Distribution des Notes des Étudiants\"**.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Histogramme_Notes_Étudiants` et enregistrez-le.\n",
    "\n",
    "### **7.7 Comparer des Séries Multiples avec des Graphiques en Courbes**\n",
    "\n",
    "#### **Exemple Pratique : Comparaison des Ventes de Deux Produits sur Plusieurs Mois**\n",
    "\n",
    "##### **Étapes pour Créer un Fichier Exemple :**\n",
    "\n",
    "1. **Créer une Nouvelle Feuille de Calcul :**\n",
    "   - Créez un nouveau document Google Sheets.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à C5, entrez les ventes de deux produits sur plusieurs mois :\n",
    "     - A1: `Mois`\n",
    "     - B1: `Produit A`\n",
    "     - C1: `Produit B`\n",
    "     - A2: `Janvier`, B2: `120`, C2: `150`\n",
    "     - A3: `Février`, B3: `130`, C3: `160`\n",
    "     - A4: `Mars`, B4: `140`, C4: `170`\n",
    "     - A5: `Avril`, B5: `150`, C5: `180`\n",
    "\n",
    "3. **Créer un Graphique en Courbes :**\n",
    "   - Sélectionnez les cellules A1 à C5.\n",
    "   - Cliquez sur **Insérer > Graphique**.\n",
    "   - Choisissez le type **Courbes** pour comparer les ventes des deux produits.\n",
    "   - Ajoutez des légendes et un titre : **\"Comparaison des Ventes des Produits A et B\"**.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Graphique_Courbes_Comparaison_Produits` et enregistrez-le.\n",
    "\n",
    "### **7.8 Graphiques en Barres Empilées pour Comparer des Sous-Catégories**\n",
    "\n",
    "#### **Exemple Pratique : Contribution des Sous-Catégories dans les Ventes Totales**\n",
    "\n",
    "##### **Étapes pour Créer un Fichier Exemple :**\n",
    "\n",
    "1. **Créer une Nouvelle Feuille de Calcul :**\n",
    "   - Créez un nouveau document Google Sheets.\n",
    "\n",
    "2. **Entrer les Données Initiales :**\n",
    "   - Dans les cellules A1 à C5, entrez les ventes des différentes sous-catégories par année :\n",
    "     - A1: `Année`\n",
    "     - B1: `Catégorie A`\n",
    "     - C1: `Catégorie B`\n",
    "     - A2: `2021`, B2: `1000`, C2: `800`\n",
    "     - A3: `2022`, B3: `1500`, C3: `1200`\n",
    "     - A4: `2023`, B4: `1800`, C4: `1600`\n",
    "     - A5: `2024`, B5: `2000`, C5: `1900`\n",
    "\n",
    "3. **Créer un Graphique en Barres Empilées :**\n",
    "   - Sélectionnez les cellules A1 à C5.\n",
    "   - Cliquez sur **Insérer > Graphique**.\n",
    "   - Choisissez le type **Barres Empilées** pour montrer la contribution de chaque sous-catégorie.\n",
    "   - Ajoutez un titre : **\"Contribution des Catégories dans les Ventes Totales\"**.\n",
    "\n",
    "4. **Sauvegarder le Fichier :**\n",
    "   - Nommez le fichier `Graphique_Barres_Empilées_Ventes` et enregistrez-le.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
